spring:
  profiles: azure
  datasource:
    url: jdbc:mysql://localhost:3306/azure_db
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      dll-auto: update
server:
  port: 8082

---
spring:
  profiles: amazon
  datasource:
    url: jdbc:mysql://localhost:3306/amazon_db
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      dll-auto: update
server:
  port: 8081

amazon:
  credentials:
    accessKey: AKIA4CR3QRBTKT2NERXI
    secretKey: 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
---
